### PR TITLE
Carousel card banner

### PR DESCRIPTION
**Pull request by chadfawcett**
123461314_412160799782259_4579704183556331763_n
123371100_641780999846310_1998343681678962464_n
123626714_1541828756004023_5554854219777759106_n
123959097_400142941370927_2197125136664011699_n

Resolves [pe1539](https://app.clubhouse.io/parks/story/1539/add-advisories-and-park-status-banners-to-the-carouselcard-component)

### CODE REVIEW

**Review by mccullochk — APPROVED** [review]
Looks good @chadfawcett. I have two small questions:

1) You've set it up to switch from showing part of the alert/advisory headline to showing `X Alerts/Advisories` if there is more than 1. I'd assumed that even if there was only one it would still just show `1 Alert/Advisory`. If you've had a discussion on this and are sure what you've implemented is the correct behaviour then ignore me. 

2) When working on the AlertAccordion I decided that it made more sense to split up the advisories and alerts when pulling that data in from the "api". What do you think about that instead of having to do a check at the component level? You don't need to change it here. We can make a separate task for it, I just want to get your opinion on that approach.

**Comment by chadfawcett** [comment]
@mccullochk 

1. Looking at the design it seemed like they were showing the headline when there was only one alert, so that's what I went with. (Examples were "Rushing water conditions" and "Park closed". I'd personally be okay with either, was just trying to follow the designs as I assumed that's what has been approved.

2. I took a look at your PR to try to see what you had done there, but that portion wasn't committed (from what I could tell at least). My thinking was between having the advisories actually attached to the park or just their ID (like the facilities and activities). I hadn't thought about separating between alerts and advisories. I think my intuition would be to leave them together, as that's how the data is, but I can also see the benefits of separating them.

**Comment by mccullochk** [comment]
@chadfawcett, yeah I did not include it in the `AlertAccordion` PR. It will/would be part of the `Park Details` page PR. Let's leave these things as they are and I can circle back on the first point with Lindsey in Clubhouse or Slack so that we can get this merged in before you leave 🙂

**Comment by chadfawcett** [comment]
Thanks @mccullochk

**Pull request merged**
