### PR TITLE
Carousel Card component

### PR DESCRIPTION
**Pull request by mccullochk**
## Notes
- This does not include the the warning/alert banner
- The colour of the "favourited" heart will probably change once we've decided on a colour scheme
- A future iteration might be necessary to including the park type symbol and name 

Resolves [pe1110](https://app.clubhouse.io/parks/story/1110/carousel-card-component)

### CODE REVIEW

**Comment by chrisfosterelli** [comment]
@mccullochk Hey Kaileen! What is needed further to move this to a reviewable state?

**Comment by mccullochk** [comment]
@chrisfosterelli, this component is undergoing further design changes so I've been waiting for those things to be sorted out before continuing this.

**Comment by chrisfosterelli** [comment]
@mccullochk Gotcha, if this is good except for the design changes we can get this reviewed and merged as-is. Then, any approved designs will be treated as new dev tasks (elaborated on in [Clubhouse here](https://app.clubhouse.io/parks/story/1110/carousel-card-component#activity-1343))

**Review by chadfawcett — APPROVED** [review]
Looks good to me @mccullochk !

**Pull request merged**
